#!/usr/bin/env bash
#
# build.sh — Generates the design-system bundles from source files.
#
# Run this whenever you change a source file, then commit both the source and
# the regenerated bundle.
#
# Usage:
#   bash build.sh
#

# Stop the script if any command fails
set -e

# Get the directory where this script lives, so it works no matter where you run it from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Make sure the bundles folder exists
mkdir -p bundles

# Today's date, used in the generated header comment
BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')

# Version, read from the VERSION file. This is what lets any copy of a bundle —
# including one frozen into a project months ago — identify itself. Bump it in
# VERSION before building, then tag the commit with the same number.
VERSION=$(tr -d ' \n\r\t' < VERSION)
if [ -z "$VERSION" ]; then
  echo "ERROR: VERSION file is missing or empty." >&2
  exit 1
fi
echo "Version $VERSION"

# Output names. These are named after what the files are, and they match what
# a project calls them once the bundles are copied in at export time, so the
# same filename applies in the repo, on the CDN, and inside a delivered site.
CSS_OUT="bundles/design-system.css"
JS_OUT="bundles/design-system.js"

# DEPRECATED aliases. The bundles used to be called all.css / all.js, and live
# projects still link those URLs. They are written as identical copies so
# nothing breaks mid-switch. Delete these two lines — and the copies at the
# bottom of this script — once every project has been relinked. See README.
CSS_ALIAS="bundles/all.css"
JS_ALIAS="bundles/all.js"

# ============================================================
# Build $CSS_OUT
# ============================================================

echo "Building $CSS_OUT..."

# Header comment so anyone opening the bundle knows it's auto-generated
cat > $CSS_OUT <<EOF
/* ============================================================
 * design-system.css — Auto-generated bundle. DO NOT EDIT THIS FILE.
 *
 * design-system v$VERSION
 * Built: $BUILD_DATE
 *
 * To make changes, edit the source files in /global or /components,
 * then run: bash build.sh
 * ============================================================ */

EOF

# CSS @import rules must appear before all other rules per CSS spec.
# Step 1: collect every @import line from all source files and write them first.
# Step 2: concatenate all source files with @import lines stripped.

ALL_CSS_FILES=()
# normalized.css must be first — it's the reset that everything else builds on
[ -f "global/normalized.css" ] && ALL_CSS_FILES+=("global/normalized.css")
for file in global/*.css; do [ -f "$file" ] && [ "$file" != "global/normalized.css" ] && ALL_CSS_FILES+=("$file"); done
for dir in components/*/; do
  for file in "$dir"*.css; do [ -f "$file" ] && ALL_CSS_FILES+=("$file"); done
done

# Step 1 — hoist @imports
for file in "${ALL_CSS_FILES[@]}"; do
  if grep -q "@import" "$file"; then
    echo "" >> $CSS_OUT
    echo "/* ---- @imports from $file ---- */" >> $CSS_OUT
    grep "@import" "$file" >> $CSS_OUT
    echo "  + @imports from $file"
  fi
done

# Step 2 — concatenate all CSS, skipping @import lines
for file in "${ALL_CSS_FILES[@]}"; do
  echo "" >> $CSS_OUT
  echo "/* ---- $file ---- */" >> $CSS_OUT
  grep -v "@import" "$file" >> $CSS_OUT
  echo "  + $file"
done

# ============================================================
# Build $JS_OUT
# ============================================================

echo ""
echo "Building $JS_OUT..."

cat > $JS_OUT <<EOF
/* ============================================================
 * design-system.js — Auto-generated bundle. DO NOT EDIT THIS FILE.
 *
 * design-system v$VERSION
 * Built: $BUILD_DATE
 *
 * To make changes, edit the source files in /global or /components,
 * then run: bash build.sh
 * ============================================================ */

/* Lets any page report which bundle it actually loaded:
   console.log(window.DS_VERSION) */
window.DS_VERSION = "$VERSION";
window.DS_BUILT = "$BUILD_DATE";

EOF

# Add global JS
for file in global/*.js; do
  if [ -f "$file" ]; then
    echo "" >> $JS_OUT
    echo "/* ---- $file ---- */" >> $JS_OUT
    cat "$file" >> $JS_OUT
    echo "  + $file"
  fi
done

# Add component JS
for dir in components/*/; do
  for file in "$dir"*.js; do
    if [ -f "$file" ]; then
      echo "" >> $JS_OUT
      echo "/* ---- $file ---- */" >> $JS_OUT
      cat "$file" >> $JS_OUT
      echo "  + $file"
    fi
  done
done

# ============================================================
# Deprecated aliases — see the note near the top of this file
# ============================================================

cp $CSS_OUT $CSS_ALIAS
cp $JS_OUT $JS_ALIAS

# ============================================================
# Done
# ============================================================

echo ""
echo "Done!"
echo "  $CSS_OUT ($(wc -l < $CSS_OUT) lines)"
echo "  $JS_OUT  ($(wc -l < $JS_OUT) lines)"
echo "  + $CSS_ALIAS / $JS_ALIAS (deprecated aliases)"
echo ""
echo "Don't forget to commit both the source files AND the regenerated bundles."
