#!/usr/bin/env bash
#
# build.sh — Generates bundles/all.css and bundles/all.js from source files.
#
# Run this whenever you change a source file, then commit both the source and
# the regenerated bundle.
#
# Usage:
#   bash build.sh
#

# Stop the script if any command fails
set -e

# Get the directory where this script lives, so it works no matter where you run it from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Make sure the bundles folder exists
mkdir -p bundles

# Today's date, used in the generated header comment
BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')

# ============================================================
# Build bundles/all.css
# ============================================================

echo "Building bundles/all.css..."

# Header comment so anyone opening the bundle knows it's auto-generated
cat > bundles/all.css <<EOF
/* ============================================================
 * all.css — Auto-generated bundle. DO NOT EDIT THIS FILE.
 *
 * To make changes, edit the source files in /global or /components,
 * then run: bash build.sh
 *
 * Built: $BUILD_DATE
 * ============================================================ */

EOF

# CSS @import rules must appear before all other rules per CSS spec.
# Step 1: collect every @import line from all source files and write them first.
# Step 2: concatenate all source files with @import lines stripped.

ALL_CSS_FILES=()
for file in global/*.css; do [ -f "$file" ] && ALL_CSS_FILES+=("$file"); done
for dir in components/*/; do
  for file in "$dir"*.css; do [ -f "$file" ] && ALL_CSS_FILES+=("$file"); done
done

# Step 1 — hoist @imports
for file in "${ALL_CSS_FILES[@]}"; do
  if grep -q "@import" "$file"; then
    echo "" >> bundles/all.css
    echo "/* ---- @imports from $file ---- */" >> bundles/all.css
    grep "@import" "$file" >> bundles/all.css
    echo "  + @imports from $file"
  fi
done

# Step 2 — concatenate all CSS, skipping @import lines
for file in "${ALL_CSS_FILES[@]}"; do
  echo "" >> bundles/all.css
  echo "/* ---- $file ---- */" >> bundles/all.css
  grep -v "@import" "$file" >> bundles/all.css
  echo "  + $file"
done

# ============================================================
# Build bundles/all.js
# ============================================================

echo ""
echo "Building bundles/all.js..."

cat > bundles/all.js <<EOF
/* ============================================================
 * all.js — Auto-generated bundle. DO NOT EDIT THIS FILE.
 *
 * To make changes, edit the source files in /global or /components,
 * then run: bash build.sh
 *
 * Built: $BUILD_DATE
 * ============================================================ */

EOF

# Add global JS
for file in global/*.js; do
  if [ -f "$file" ]; then
    echo "" >> bundles/all.js
    echo "/* ---- $file ---- */" >> bundles/all.js
    cat "$file" >> bundles/all.js
    echo "  + $file"
  fi
done

# Add component JS
for dir in components/*/; do
  for file in "$dir"*.js; do
    if [ -f "$file" ]; then
      echo "" >> bundles/all.js
      echo "/* ---- $file ---- */" >> bundles/all.js
      cat "$file" >> bundles/all.js
      echo "  + $file"
    fi
  done
done

# ============================================================
# Done
# ============================================================

echo ""
echo "Done!"
echo "  bundles/all.css ($(wc -l < bundles/all.css) lines)"
echo "  bundles/all.js  ($(wc -l < bundles/all.js) lines)"
echo ""
echo "Don't forget to commit both the source files AND the regenerated bundles."
